BBPATH .= ":${LAYERDIR}"
BBPATH .= ":${LAYERDIR}/deps/meta-flutter"
BBPATH .= ":${LAYERDIR}/deps/meta-clang"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILES += "${LAYERDIR}/deps/meta-flutter/recipes-graphics/*/*.bb \
            ${LAYERDIR}/deps/meta-flutter/recipes-devtool/*/*.bb"

BBFILE_COLLECTIONS += "meta-bolt-flutter"
BBFILE_PATTERN_meta-bolt-flutter = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bolt-flutter = "10"

LAYERDEPENDS_meta-bolt-flutter = "bolt-base"
LAYERSERIES_COMPAT_meta-bolt-flutter = "kirkstone"

#DISTRO_FEATURES:append = " cobalt-25"

MIDDLEWARE_ARCH ??= "${TUNE_PKGARCH}"

BBMULTICONFIG:remove = "arm64"
BBMULTICONFIG:remove = "amd64"

CMF_GITHUB_ROOT ?= "git://github.com/rdkcentral"
CMF_GITHUB_PROTOCOL = "https"
CMF_GITHUB_BRANCH = "nobranch=1"
CMF_GITHUB_SRC_URI_SUFFIX = "protocol=${CMF_GITHUB_PROTOCOL};${CMF_GITHUB_BRANCH}"
